### ISSUE TITLE
Erorr when minimizing in ubuntu: java.net.BindException: Address already in use (Bind failed)

### ISSUE THREAD

**Issue by cancub** [repeats/Repeat#16]
Every time I start up Repeat (running the latest release), set it to run in the background, disown it and then minimize, I get the following error:

```
Apr 04, 2018 3:00:07 PM core.ipc.repeatServer.ControllerServer$1 run
SEVERE: IO Exception when starting server
java.net.BindException: Address already in use (Bind failed)
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at java.net.ServerSocket.<init>(ServerSocket.java:128)
	at core.ipc.repeatServer.ControllerServer$1.run(ControllerServer.java:44)

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000002306, pid=7487, tid=0x00007f7d6c50f700
#
# JRE version: OpenJDK Runtime Environment (8.0_162-b12) (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.162-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x0000000000002306
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/<name>/Documents/Repeat/hs_err_pid7487.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

```

**Comment by cancub** [comment]
Error report file:

[hs_err_pid7487.log](https://github.com/repeats/Repeat/files/1877258/hs_err_pid7487.log)

**Comment by hptruong93** [comment]
Is this Linux or Windows? How exactly did you "set it to run in the background"?

The following works fine on my Linux machine
$java -jar Repeat.jar &
$disown
$exit

Did you mean
$java -jar Repeat.jar
$<Ctrl + Z>
$disown
?

**Comment by cancub** [comment]
Ubuntu 16.04 on my end. The first procedure is what I've been doing, i.e.,

```
$ java -jar Repeat.jar &
$ disown
``` 
Regardless of whether or not I exit the terminal, minimizing the Repeat window has the same effect of throwing this error.

**Comment by cancub** [comment]
I don't seem to be able to reproduce this myself now

**Comment by hptruong93** [comment]
I'll close as not reproducible then.
