### ISSUE TITLE
Cannot open UI: Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!

### ISSUE THREAD

**Issue by DDzwiedziu** [repeats/Repeat#39]
When trying to use “Show UI” from the tray icon nothing happens and the following exception is thrown:

```
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
        at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:381)
        at java.desktop/java.awt.Desktop.browse(Desktop.java:531)
        at frontEnd.MinimizedFrame.show(MinimizedFrame.java:78)
        at frontEnd.MinimizedFrame.access$0(MinimizedFrame.java:70)
        at frontEnd.MinimizedFrame$1.actionPerformed(MinimizedFrame.java:41)
        at java.desktop/java.awt.MenuItem.processActionEvent(MenuItem.java:692)
        at java.desktop/java.awt.MenuItem.processEvent(MenuItem.java:651)
        at java.desktop/java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:378)
        at java.desktop/java.awt.MenuComponent.dispatchEvent(MenuComponent.java:367)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by hptruong93** [comment]
Can you include more details? What operating system are you running? What browser do you have?

Have you tried opening a browser and going directly to the local web page? After started there's a message printing out the local web page hosting the UI. It's by default http://localhost:65401

**Comment by DDzwiedziu** [comment]
Firefox, current Ubuntu latest at that time.

And yes, directly opening it it works, but I've assumed it wanted to use something similar like `xdg-open` and that has borked.

**Comment by hptruong93** [comment]
The actual code is here

https://github.com/repeats/Repeat/blob/d9c209fbe2c1c80fadf053236aa2fe457784921c/src/frontEnd/MinimizedFrame.java#L78

I guess I'll try to find another way to do the browse action.
